---
- name: Creates dirs
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    mode: '0755'
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
  loop:
    - "/home/{{ default_user }}/.config"
    - "/home/{{ default_user }}/.config/autostart"
    - "/home/{{ default_user }}/.config/wireplumber/main.lua.d"

# Fix from https://forum.qubes-os.org/t/audio-qube/20685/217
- name: Add wireplumber config hotfix for Qubes
  when: ansible_os_family == 'Debian'
  ansible.builtin.copy:
    src: files/home/sys-audio/.config/wireplumber/main.lua.d/89-qubes.lua
    dest: /home/{{ default_user }}/.config/wireplumber/main.lua.d/89-qubes.lua
    mode: '0644'
    owner: "{{ default_user }}"
    group: "{{ default_user }}"

- name: Uncomment FastConnectable from /rw/config/etc-bluetooth/main.conf and set True
  become: true
  ansible.builtin.replace:
    path: /etc/bluetooth/main.conf
    regexp: '^#?FastConnectable\s*=\s*\w+'
    replace: 'FastConnectable = true'

- name: Create /rw/config/qubes-bind-dirs.d
  become: true
  ansible.builtin.file:
    state: directory
    path: /rw/config/qubes-bind-dirs.d
    mode: '0755'
    owner: root
    group: root

- name: Create /rw/config/qubes-bind-dirs.d/50_user.conf
  become: true
  ansible.builtin.copy:
    content: |
      binds+=( '/etc/bluetooth' )
      binds+=( '/var/lib/bluetooth' )
    dest: /rw/config/qubes-bind-dirs.d/50_user.conf
    mode: '0644'
    owner: root
    group: root

- name: Add autostart to qvm-start-daemon.desktop
  ansible.builtin.copy:
    content: |
      [Desktop Entry]
      Name=Qubes Guid/Pacat
      Comment=Starts GUI/AUDIO daemon for Qubes VMs
      Icon=qubes
      Exec=qvm-start-daemon --all --watch
      Terminal=False
      Type=Application
    dest: /home/{{ default_user }}/.config/autostart/qvm-start-daemon.desktop
    mode: '0644'
    owner: "{{ default_user }}"
    group: "{{ default_user }}"

- name: Add blueman-manager to autostart
  ansible.builtin.copy:
    content: |
      [Desktop Entry]
      Name=Blueman Manager
      Comment=Starts Blueman Manager
      Icon=qubes
      Exec=blueman-manager
      Terminal=False
      Type=Application
    dest: /home/{{ default_user }}/.config/autostart/blueman-manager.desktop
    mode: '0644'
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
