---
- name: Creates dirs
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    mode: '0755'
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
  loop:
    - "/home/{{ default_user }}/.config"
    - "/home/{{ default_user }}/.config/autostart"

- name: Create /rw/config dirs for save bluetooth data after reboot
  become: true
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    mode: '0755'
    owner: root
    group: root
  loop:
    - /rw/config/etc-bluetooth
    - /rw/config/var-lib-bluetooth

- name: Copy default files from /etc/bluetooth/* to /rw/config/etc-bluetooth if not exists
  become: true
  ansible.builtin.copy:
    src: "/etc/bluetooth/{{ item }}"
    dest: "/rw/config/etc-bluetooth/{{ item }}"
    remote_src: true
    owner: root
    group: root
    mode: '0644'
    force: false
  loop:
    - input.conf
    - main.conf
    - network.conf

- name: Uncomment FastConnectable from /rw/config/etc-bluetooth/main.conf and set True
  become: true
  ansible.builtin.replace:
    path: /rw/config/etc-bluetooth/main.conf
    regexp: '^#?FastConnectable\s*=\s*\w+'
    replace: 'FastConnectable = true'

- name: Create /rw/config/qubes-bind-dirs.d
  become: true
  ansible.builtin.file:
    state: directory
    path: /rw/config/qubes-bind-dirs.d
    mode: '0755'
    owner: root
    group: root

- name: Create /rw/config/qubes-bind-dirs.d/50_user.conf
  become: true
  ansible.builtin.copy:
    content: |
      binds+=( '/etc/bluetooth' )
      binds+=( '/var/lib/bluetooth' )
    dest: /rw/config/qubes-bind-dirs.d/50_user.conf
    mode: '0644'
    owner: root
    group: root

- name: Add autostart to pulseaudio.desktop
  ansible.builtin.copy:
    content: |
      [Desktop Entry]
      Name=Pulseaudio
      Comment=Starts Pulseaudio
      Icon=qubes
      Exec=pulseaudio
      Terminal=False
      Type=Application
    dest: /home/{{ default_user }}/.config/autostart/pulseaudio.desktop
    mode: '0644'
    owner: "{{ default_user }}"
    group: "{{ default_user }}"

- name: Add autostart to qvm-start-daemon.desktop
  ansible.builtin.copy:
    content: |
      [Desktop Entry]
      Name=Qubes Guid/Pacat
      Comment=Starts GUI/AUDIO daemon for Qubes VMs
      Icon=qubes
      Exec=qvm-start-daemon --all --watch
      Terminal=False
      Type=Application
    dest: /home/{{ default_user }}/.config/autostart/qvm-start-daemon.desktop
    mode: '0644'
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
