[dom0]
localhost

[dom0:vars]
ansible_connection=local
# Requires Qubes 4.3+ (qubes-ansible is only available there)
# For debian:
base_template=debian-13-xfce
# For fedora:
# base_template=fedora-44-xfce

# If set true, USB audio devices will be automatically attached to the VMs
enable_usb_auto_attach=false

[appvms]
sys-audio

[appvms:vars]
ansible_connection=qubesos.core.qubes
ansible_user=root

[templatevms]
# For debian:
debian-13-xfce-sys-audio
# For fedora:
# fedora-44-xfce-sys-audio

[templatevms:vars]
ansible_connection=qubesos.core.qubes
ansible_user=root
