---
# TODO: Fix changed_when to be more accurate
- name: Install template if not exists (it may take up to several minutes)
  ansible.builtin.command:
    cmd: qvm-template install {{ base_template }}
    creates: /var/lib/qubes/vm-templates/{{ base_template }}
  changed_when: true

- name: Copy template to {{ templatevm_sys_audio }}
  become: true
  ansible.builtin.command:
    cmd: qvm-clone {{ base_template }} {{ templatevm_sys_audio }}
    creates: /var/lib/qubes/vm-templates/{{ templatevm_sys_audio }}
  changed_when: true
