---
- name: Create AppVM {{ appvm_sys_audio }}
  become: true
  ansible.builtin.command:
    cmd: |
      qvm-create \
        --label {{ appvm_label }} \
        --template {{ templatevm_sys_audio }} \
        --class AppVM \
        --property netvm= \
        --property memory={{ appvm_maxmemory }} \
        --property vcpus={{ appvm_vcpus }} \
        --property autostart=True \
        --property virt_mode=hvm \
        {{ appvm_sys_audio }}
    creates: /var/lib/qubes/appvms/{{ appvm_sys_audio }}
  changed_when: true
