---
- name: Install qubes-audio-dom0
  become: true
  ansible.builtin.command:
    cmd: |
      qubes-dom0-update -y qubes-audio-dom0
  changed_when: true

- name: Add audiovm-sys-audio tag to {{ appvm_sys_audio }}
  ansible.builtin.command:
    cmd: |
      qvm-tags \
        {{ appvm_sys_audio }}
        add \
        {{ appvm_sys_audio_tag }}
  changed_when: true

- name: Add audiovm service to sys-audio AppVM
  ansible.builtin.command:
    cmd: |
      qvm-service \
        {{ appvm_sys_audio }} \
        add \
        audiovm on
  changed_when: true

- name: Set sys-audio as default audio device
  ansible.builtin.command:
    cmd: |
      qubes-prefs \
        default_audiovm \
        {{ appvm_sys_audio }}
  changed_when: true

- name: Add PCI devices to sys-audio
  ansible.builtin.command:
    cmd: |
      for device in $(qvm-pci | grep -i Audio | awk '{print $1}')
      do
        qvm-pci \
          attach {{ appvm_sys_audio }} \
          $device \
          --persistent \
          -o no-strict-reset=True
      done
  changed_when: true

  # TODO: Add USB device to sys-audio

- name: Add 81-sys-audio.policy to /etc/qubes/policy.d/81-sys-audio.policy
  become: true
  ansible.builtin.template:
    src: files/etc/qubes/policy.d/81-sys-audio.policy.j2
    dest: /etc/qubes/policy.d/81-sys-audio.policy
    mode: '0644'
    owner: root
    group: root

  # If you want to use the USB device in sys-audio, you need to add workaround
  # to start sys-usb AppVM when sys-audio is started
  # Based on https://forum.qubes-os.org/t/unable-to-get-sys-audio-qube-to-auto-start-on-boot/25957/22
- name: Add /etc/libvirt/hooks/libxl file
  become: true
  ansible.builtin.template:
    src: files/etc/libvirt/hooks/libxl.j2
    dest: /etc/libvirt/hooks/libxl
    mode: '0755'
    owner: root
    group: root
